//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Stocks.ServiceClients.ETrade.ObjectModel {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AccountBalanceResponse {
        
        private uint accountIdField;
        
        private string accountTypeField;
        
        private string optionLevelField;
        
        private AccountBalanceResponseAccountBalance accountBalanceField;
        
        private AccountBalanceResponseMarginAccountBalance marginAccountBalanceField;
        
        /// <remarks/>
        public uint accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string accountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
            }
        }
        
        /// <remarks/>
        public string optionLevel {
            get {
                return this.optionLevelField;
            }
            set {
                this.optionLevelField = value;
            }
        }
        
        /// <remarks/>
        public AccountBalanceResponseAccountBalance accountBalance {
            get {
                return this.accountBalanceField;
            }
            set {
                this.accountBalanceField = value;
            }
        }
        
        /// <remarks/>
        public AccountBalanceResponseMarginAccountBalance marginAccountBalance {
            get {
                return this.marginAccountBalanceField;
            }
            set {
                this.marginAccountBalanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountBalanceResponseAccountBalance {
        
        private decimal cashAvailableForWithdrawalField;
        
        private decimal netAccountValueField;
        
        private decimal netCashField;
        
        private decimal sweepDepositAmountField;
        
        private decimal totalLongValueField;
        
        private decimal totalSecuritiesMktValueField;
        
        /// <remarks/>
        public decimal cashAvailableForWithdrawal {
            get {
                return this.cashAvailableForWithdrawalField;
            }
            set {
                this.cashAvailableForWithdrawalField = value;
            }
        }
        
        /// <remarks/>
        public decimal netAccountValue {
            get {
                return this.netAccountValueField;
            }
            set {
                this.netAccountValueField = value;
            }
        }
        
        /// <remarks/>
        public decimal netCash {
            get {
                return this.netCashField;
            }
            set {
                this.netCashField = value;
            }
        }
        
        /// <remarks/>
        public decimal sweepDepositAmount {
            get {
                return this.sweepDepositAmountField;
            }
            set {
                this.sweepDepositAmountField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalLongValue {
            get {
                return this.totalLongValueField;
            }
            set {
                this.totalLongValueField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalSecuritiesMktValue {
            get {
                return this.totalSecuritiesMktValueField;
            }
            set {
                this.totalSecuritiesMktValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountBalanceResponseMarginAccountBalance {
        
        private AccountBalanceResponseMarginAccountBalanceDtBalance dtBalanceField;
        
        private decimal fedCallField;
        
        private decimal marginBalanceField;
        
        private decimal marginBalanceWithdrawalField;
        
        private decimal marginEquityField;
        
        private decimal marginableSecuritiesField;
        
        private decimal maxAvailableForWithdrawalField;
        
        private decimal minEquityCallField;
        
        private decimal nonMarginableSecuritiesAndOptionsField;
        
        private decimal totalShortValueField;
        
        private decimal shortReserveField;
        
        /// <remarks/>
        public AccountBalanceResponseMarginAccountBalanceDtBalance dtBalance {
            get {
                return this.dtBalanceField;
            }
            set {
                this.dtBalanceField = value;
            }
        }
        
        /// <remarks/>
        public decimal fedCall {
            get {
                return this.fedCallField;
            }
            set {
                this.fedCallField = value;
            }
        }
        
        /// <remarks/>
        public decimal marginBalance {
            get {
                return this.marginBalanceField;
            }
            set {
                this.marginBalanceField = value;
            }
        }
        
        /// <remarks/>
        public decimal marginBalanceWithdrawal {
            get {
                return this.marginBalanceWithdrawalField;
            }
            set {
                this.marginBalanceWithdrawalField = value;
            }
        }
        
        /// <remarks/>
        public decimal marginEquity {
            get {
                return this.marginEquityField;
            }
            set {
                this.marginEquityField = value;
            }
        }
        
        /// <remarks/>
        public decimal marginableSecurities {
            get {
                return this.marginableSecuritiesField;
            }
            set {
                this.marginableSecuritiesField = value;
            }
        }
        
        /// <remarks/>
        public decimal maxAvailableForWithdrawal {
            get {
                return this.maxAvailableForWithdrawalField;
            }
            set {
                this.maxAvailableForWithdrawalField = value;
            }
        }
        
        /// <remarks/>
        public decimal minEquityCall {
            get {
                return this.minEquityCallField;
            }
            set {
                this.minEquityCallField = value;
            }
        }
        
        /// <remarks/>
        public decimal nonMarginableSecuritiesAndOptions {
            get {
                return this.nonMarginableSecuritiesAndOptionsField;
            }
            set {
                this.nonMarginableSecuritiesAndOptionsField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalShortValue {
            get {
                return this.totalShortValueField;
            }
            set {
                this.totalShortValueField = value;
            }
        }
        
        /// <remarks/>
        public decimal shortReserve {
            get {
                return this.shortReserveField;
            }
            set {
                this.shortReserveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountBalanceResponseMarginAccountBalanceDtBalance {
        
        private decimal dtCashBalanceField;
        
        private decimal dtMarginBalanceField;
        
        private decimal dtMarginableSecuritiesField;
        
        private decimal dtNonMarginableSecuritiesAndOptionsField;
        
        private string dtStatusField;
        
        /// <remarks/>
        public decimal dtCashBalance {
            get {
                return this.dtCashBalanceField;
            }
            set {
                this.dtCashBalanceField = value;
            }
        }
        
        /// <remarks/>
        public decimal dtMarginBalance {
            get {
                return this.dtMarginBalanceField;
            }
            set {
                this.dtMarginBalanceField = value;
            }
        }
        
        /// <remarks/>
        public decimal dtMarginableSecurities {
            get {
                return this.dtMarginableSecuritiesField;
            }
            set {
                this.dtMarginableSecuritiesField = value;
            }
        }
        
        /// <remarks/>
        public decimal dtNonMarginableSecuritiesAndOptions {
            get {
                return this.dtNonMarginableSecuritiesAndOptionsField;
            }
            set {
                this.dtNonMarginableSecuritiesAndOptionsField = value;
            }
        }
        
        /// <remarks/>
        public string dtStatus {
            get {
                return this.dtStatusField;
            }
            set {
                this.dtStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AccountListResponse {
        
        private AccountListResponseAccount[] accountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Account")]
        public AccountListResponseAccount[] Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountListResponseAccount {
        
        private string accountDescField;
        
        private uint accountIdField;
        
        private string marginLevelField;
        
        private decimal netAccountValueField;
        
        private string registrationTypeField;
        
        /// <remarks/>
        public string accountDesc {
            get {
                return this.accountDescField;
            }
            set {
                this.accountDescField = value;
            }
        }
        
        /// <remarks/>
        public uint accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string marginLevel {
            get {
                return this.marginLevelField;
            }
            set {
                this.marginLevelField = value;
            }
        }
        
        /// <remarks/>
        public decimal netAccountValue {
            get {
                return this.netAccountValueField;
            }
            set {
                this.netAccountValueField = value;
            }
        }
        
        /// <remarks/>
        public string registrationType {
            get {
                return this.registrationTypeField;
            }
            set {
                this.registrationTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AccountPositionsResponse {
        
        private uint accountIdField;
        
        private short countField;
        
        private string markerField;
        
        private AccountPositionsResponseAccountPosition[] accountPositionsField;
        
        /// <remarks/>
        public uint accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public short count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public string marker {
            get {
                return this.markerField;
            }
            set {
                this.markerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AccountPosition", IsNullable=false)]
        public AccountPositionsResponseAccountPosition[] AccountPositions {
            get {
                return this.accountPositionsField;
            }
            set {
                this.accountPositionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountPositionsResponseAccountPosition {
        
        private decimal costBasisField;
        
        private string descriptionField;
        
        private string longOrShortField;
        
        private bool marginableField;
        
        private AccountPositionsResponseAccountPositionProductId productIdField;
        
        private decimal qtyField;
        
        private decimal marketValueField;
        
        /// <remarks/>
        public decimal costBasis {
            get {
                return this.costBasisField;
            }
            set {
                this.costBasisField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string longOrShort {
            get {
                return this.longOrShortField;
            }
            set {
                this.longOrShortField = value;
            }
        }
        
        /// <remarks/>
        public bool marginable {
            get {
                return this.marginableField;
            }
            set {
                this.marginableField = value;
            }
        }
        
        /// <remarks/>
        public AccountPositionsResponseAccountPositionProductId productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal marketValue {
            get {
                return this.marketValueField;
            }
            set {
                this.marketValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountPositionsResponseAccountPositionProductId {
        
        private string symbolField;
        
        private string typeCodeField;
        
        /// <remarks/>
        public string symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string typeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class GetOrderListResponse {
        
        private GetOrderListResponseOrderListResponse orderListResponseField;
        
        /// <remarks/>
        public GetOrderListResponseOrderListResponse orderListResponse {
            get {
                return this.orderListResponseField;
            }
            set {
                this.orderListResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetOrderListResponseOrderListResponse {
        
        private int countField;
        
        private string markerField;
        
        private GetOrderListResponseOrderListResponseOrderDetails[] orderDetailsField;
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public string marker {
            get {
                return this.markerField;
            }
            set {
                this.markerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OrderDetails", IsNullable=false)]
        public GetOrderListResponseOrderListResponseOrderDetails[] orderDetails {
            get {
                return this.orderDetailsField;
            }
            set {
                this.orderDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetOrderListResponseOrderListResponseOrderDetails {
        
        private GetOrderListResponseOrderListResponseOrderDetailsOrder orderField;
        
        /// <remarks/>
        public GetOrderListResponseOrderListResponseOrderDetailsOrder order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetOrderListResponseOrderListResponseOrderDetailsOrder {
        
        private long orderIdField;
        
        private ulong orderPlacedTimeField;
        
        private ulong orderExecutedTimeField;
        
        private bool orderExecutedTimeFieldSpecified;
        
        private decimal orderValueField;
        
        private string orderStatusField;
        
        private string orderTypeField;
        
        private string orderTermField;
        
        private string priceTypeField;
        
        private decimal limitPriceField;
        
        private decimal stopPriceField;
        
        private GetOrderListResponseOrderListResponseOrderDetailsOrderLegDetails[] legDetailsField;
        
        private long replacedByOrderIdField;
        
        private bool replacedByOrderIdFieldSpecified;
        
        private bool allOrNoneField;
        
        /// <remarks/>
        public long orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public ulong orderPlacedTime {
            get {
                return this.orderPlacedTimeField;
            }
            set {
                this.orderPlacedTimeField = value;
            }
        }
        
        /// <remarks/>
        public ulong orderExecutedTime {
            get {
                return this.orderExecutedTimeField;
            }
            set {
                this.orderExecutedTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderExecutedTimeSpecified {
            get {
                return this.orderExecutedTimeFieldSpecified;
            }
            set {
                this.orderExecutedTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal orderValue {
            get {
                return this.orderValueField;
            }
            set {
                this.orderValueField = value;
            }
        }
        
        /// <remarks/>
        public string orderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        public string orderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        public string orderTerm {
            get {
                return this.orderTermField;
            }
            set {
                this.orderTermField = value;
            }
        }
        
        /// <remarks/>
        public string priceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal limitPrice {
            get {
                return this.limitPriceField;
            }
            set {
                this.limitPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal stopPrice {
            get {
                return this.stopPriceField;
            }
            set {
                this.stopPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LegDetails", IsNullable=false)]
        public GetOrderListResponseOrderListResponseOrderDetailsOrderLegDetails[] legDetails {
            get {
                return this.legDetailsField;
            }
            set {
                this.legDetailsField = value;
            }
        }
        
        /// <remarks/>
        public long replacedByOrderId {
            get {
                return this.replacedByOrderIdField;
            }
            set {
                this.replacedByOrderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool replacedByOrderIdSpecified {
            get {
                return this.replacedByOrderIdFieldSpecified;
            }
            set {
                this.replacedByOrderIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool allOrNone {
            get {
                return this.allOrNoneField;
            }
            set {
                this.allOrNoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetOrderListResponseOrderListResponseOrderDetailsOrderLegDetails {
        
        private long legNumberField;
        
        private GetOrderListResponseOrderListResponseOrderDetailsOrderLegDetailsSymbolInfo symbolInfoField;
        
        private string symbolDescriptionField;
        
        private string orderActionField;
        
        private decimal orderedQuantityField;
        
        private decimal filledQuantityField;
        
        private decimal executedPriceField;
        
        private decimal estimatedCommissionField;
        
        private decimal estimatedFeesField;
        
        /// <remarks/>
        public long legNumber {
            get {
                return this.legNumberField;
            }
            set {
                this.legNumberField = value;
            }
        }
        
        /// <remarks/>
        public GetOrderListResponseOrderListResponseOrderDetailsOrderLegDetailsSymbolInfo symbolInfo {
            get {
                return this.symbolInfoField;
            }
            set {
                this.symbolInfoField = value;
            }
        }
        
        /// <remarks/>
        public string symbolDescription {
            get {
                return this.symbolDescriptionField;
            }
            set {
                this.symbolDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string orderAction {
            get {
                return this.orderActionField;
            }
            set {
                this.orderActionField = value;
            }
        }
        
        /// <remarks/>
        public decimal orderedQuantity {
            get {
                return this.orderedQuantityField;
            }
            set {
                this.orderedQuantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal filledQuantity {
            get {
                return this.filledQuantityField;
            }
            set {
                this.filledQuantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal executedPrice {
            get {
                return this.executedPriceField;
            }
            set {
                this.executedPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal estimatedCommission {
            get {
                return this.estimatedCommissionField;
            }
            set {
                this.estimatedCommissionField = value;
            }
        }
        
        /// <remarks/>
        public decimal estimatedFees {
            get {
                return this.estimatedFeesField;
            }
            set {
                this.estimatedFeesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetOrderListResponseOrderListResponseOrderDetailsOrderLegDetailsSymbolInfo {
        
        private string symbolField;
        
        private string callPutField;
        
        private short expYearField;
        
        private bool expYearFieldSpecified;
        
        private byte expMonthField;
        
        private bool expMonthFieldSpecified;
        
        private byte expDayField;
        
        private bool expDayFieldSpecified;
        
        private decimal strikePriceField;
        
        private bool strikePriceFieldSpecified;
        
        /// <remarks/>
        public string symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string callPut {
            get {
                return this.callPutField;
            }
            set {
                this.callPutField = value;
            }
        }
        
        /// <remarks/>
        public short expYear {
            get {
                return this.expYearField;
            }
            set {
                this.expYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expYearSpecified {
            get {
                return this.expYearFieldSpecified;
            }
            set {
                this.expYearFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public byte expMonth {
            get {
                return this.expMonthField;
            }
            set {
                this.expMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expMonthSpecified {
            get {
                return this.expMonthFieldSpecified;
            }
            set {
                this.expMonthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public byte expDay {
            get {
                return this.expDayField;
            }
            set {
                this.expDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expDaySpecified {
            get {
                return this.expDayFieldSpecified;
            }
            set {
                this.expDayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal strikePrice {
            get {
                return this.strikePriceField;
            }
            set {
                this.strikePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool strikePriceSpecified {
            get {
                return this.strikePriceFieldSpecified;
            }
            set {
                this.strikePriceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class EquityOrderRequest {
        
        private uint accountIdField;
        
        private string clientOrderIdField;
        
        private decimal limitPriceField;
        
        private System.Nullable<int> previewIdField;
        
        private decimal stopPriceField;
        
        private decimal stopLimitPriceField;
        
        private bool allOrNoneField;
        
        private int quantityField;
        
        private bool reserveOrderField;
        
        private int reserveQuantityField;
        
        private string symbolField;
        
        private string orderActionField;
        
        private string priceTypeField;
        
        private string routingDestinationField;
        
        private string marketSessionField;
        
        private string orderTermField;
        
        /// <remarks/>
        public uint accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string clientOrderId {
            get {
                return this.clientOrderIdField;
            }
            set {
                this.clientOrderIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal limitPrice {
            get {
                return this.limitPriceField;
            }
            set {
                this.limitPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> previewId {
            get {
                return this.previewIdField;
            }
            set {
                this.previewIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal stopPrice {
            get {
                return this.stopPriceField;
            }
            set {
                this.stopPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal stopLimitPrice {
            get {
                return this.stopLimitPriceField;
            }
            set {
                this.stopLimitPriceField = value;
            }
        }
        
        /// <remarks/>
        public bool allOrNone {
            get {
                return this.allOrNoneField;
            }
            set {
                this.allOrNoneField = value;
            }
        }
        
        /// <remarks/>
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public bool reserveOrder {
            get {
                return this.reserveOrderField;
            }
            set {
                this.reserveOrderField = value;
            }
        }
        
        /// <remarks/>
        public int reserveQuantity {
            get {
                return this.reserveQuantityField;
            }
            set {
                this.reserveQuantityField = value;
            }
        }
        
        /// <remarks/>
        public string symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string orderAction {
            get {
                return this.orderActionField;
            }
            set {
                this.orderActionField = value;
            }
        }
        
        /// <remarks/>
        public string priceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string routingDestination {
            get {
                return this.routingDestinationField;
            }
            set {
                this.routingDestinationField = value;
            }
        }
        
        /// <remarks/>
        public string marketSession {
            get {
                return this.marketSessionField;
            }
            set {
                this.marketSessionField = value;
            }
        }
        
        /// <remarks/>
        public string orderTerm {
            get {
                return this.orderTermField;
            }
            set {
                this.orderTermField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PlaceEquityOrderResponse {
        
        private PlaceEquityOrderResponseEquityOrderResponse equityOrderResponseField;
        
        /// <remarks/>
        public PlaceEquityOrderResponseEquityOrderResponse equityOrderResponse {
            get {
                return this.equityOrderResponseField;
            }
            set {
                this.equityOrderResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PlaceEquityOrderResponseEquityOrderResponse {
        
        private uint accountIdField;
        
        private bool allOrNoneField;
        
        private decimal estimatedCommissionField;
        
        private decimal estimatedTotalAmountField;
        
        private PlaceEquityOrderResponseEquityOrderResponseMessageList messageListField;
        
        private int orderNumField;
        
        private ulong orderTimeField;
        
        private int quantityField;
        
        private bool reserveOrderField;
        
        private int reserveQuantityField;
        
        private string orderTermField;
        
        private decimal limitPriceField;
        
        private decimal stopPriceField;
        
        private string symbolDescField;
        
        private string symbolField;
        
        private string orderActionField;
        
        private string priceTypeField;
        
        /// <remarks/>
        public uint accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public bool allOrNone {
            get {
                return this.allOrNoneField;
            }
            set {
                this.allOrNoneField = value;
            }
        }
        
        /// <remarks/>
        public decimal estimatedCommission {
            get {
                return this.estimatedCommissionField;
            }
            set {
                this.estimatedCommissionField = value;
            }
        }
        
        /// <remarks/>
        public decimal estimatedTotalAmount {
            get {
                return this.estimatedTotalAmountField;
            }
            set {
                this.estimatedTotalAmountField = value;
            }
        }
        
        /// <remarks/>
        public PlaceEquityOrderResponseEquityOrderResponseMessageList messageList {
            get {
                return this.messageListField;
            }
            set {
                this.messageListField = value;
            }
        }
        
        /// <remarks/>
        public int orderNum {
            get {
                return this.orderNumField;
            }
            set {
                this.orderNumField = value;
            }
        }
        
        /// <remarks/>
        public ulong orderTime {
            get {
                return this.orderTimeField;
            }
            set {
                this.orderTimeField = value;
            }
        }
        
        /// <remarks/>
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public bool reserveOrder {
            get {
                return this.reserveOrderField;
            }
            set {
                this.reserveOrderField = value;
            }
        }
        
        /// <remarks/>
        public int reserveQuantity {
            get {
                return this.reserveQuantityField;
            }
            set {
                this.reserveQuantityField = value;
            }
        }
        
        /// <remarks/>
        public string orderTerm {
            get {
                return this.orderTermField;
            }
            set {
                this.orderTermField = value;
            }
        }
        
        /// <remarks/>
        public decimal limitPrice {
            get {
                return this.limitPriceField;
            }
            set {
                this.limitPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal stopPrice {
            get {
                return this.stopPriceField;
            }
            set {
                this.stopPriceField = value;
            }
        }
        
        /// <remarks/>
        public string symbolDesc {
            get {
                return this.symbolDescField;
            }
            set {
                this.symbolDescField = value;
            }
        }
        
        /// <remarks/>
        public string symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string orderAction {
            get {
                return this.orderActionField;
            }
            set {
                this.orderActionField = value;
            }
        }
        
        /// <remarks/>
        public string priceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PlaceEquityOrderResponseEquityOrderResponseMessageList {
        
        private PlaceEquityOrderResponseEquityOrderResponseMessageListMessage messageField;
        
        /// <remarks/>
        public PlaceEquityOrderResponseEquityOrderResponseMessageListMessage message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PlaceEquityOrderResponseEquityOrderResponseMessageListMessage {
        
        private string msgDescField;
        
        private int msgCodeField;
        
        /// <remarks/>
        public string msgDesc {
            get {
                return this.msgDescField;
            }
            set {
                this.msgDescField = value;
            }
        }
        
        /// <remarks/>
        public int msgCode {
            get {
                return this.msgCodeField;
            }
            set {
                this.msgCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class QuoteResponse {
        
        private QuoteResponseQuoteData[] quoteDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QuoteData")]
        public QuoteResponseQuoteData[] QuoteData {
            get {
                return this.quoteDataField;
            }
            set {
                this.quoteDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class QuoteResponseQuoteData {
        
        private QuoteResponseQuoteDataAll allField;
        
        private string dateTimeField;
        
        private QuoteResponseQuoteDataProduct productField;
        
        /// <remarks/>
        public QuoteResponseQuoteDataAll all {
            get {
                return this.allField;
            }
            set {
                this.allField = value;
            }
        }
        
        /// <remarks/>
        public string dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        public QuoteResponseQuoteDataProduct product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class QuoteResponseQuoteDataAll {
        
        private bool adjNonAdjFlagField;
        
        private decimal annualDividendField;
        
        private decimal askField;
        
        private string askExchangeField;
        
        private ushort askSizeField;
        
        private string askTimeField;
        
        private decimal bidField;
        
        private string bidExchangeField;
        
        private ushort bidSizeField;
        
        private string bidTimeField;
        
        private decimal chgCloseField;
        
        private decimal chgClosePrcnField;
        
        private string companyNameField;
        
        private byte daysToExpirationField;
        
        private string dirLastField;
        
        private decimal dividendField;
        
        private decimal epsField;
        
        private decimal estEarningsField;
        
        private string exDivDateField;
        
        private string exchgLastTradeField;
        
        private string fsiField;
        
        private decimal highField;
        
        private decimal high52Field;
        
        private decimal highAskField;
        
        private decimal highBidField;
        
        private decimal lastTradeField;
        
        private decimal lowField;
        
        private decimal low52Field;
        
        private decimal lowAskField;
        
        private decimal lowBidField;
        
        private uint numTradesField;
        
        private decimal openField;
        
        private byte openInterestField;
        
        private object optionStyleField;
        
        private object optionUnderlierField;
        
        private decimal prevCloseField;
        
        private uint prevDayVolumeField;
        
        private string primaryExchangeField;
        
        private string symbolDescField;
        
        private decimal todayCloseField;
        
        private uint totalVolumeField;
        
        private byte upcField;
        
        private uint volume10DayField;
        
        /// <remarks/>
        public bool adjNonAdjFlag {
            get {
                return this.adjNonAdjFlagField;
            }
            set {
                this.adjNonAdjFlagField = value;
            }
        }
        
        /// <remarks/>
        public decimal annualDividend {
            get {
                return this.annualDividendField;
            }
            set {
                this.annualDividendField = value;
            }
        }
        
        /// <remarks/>
        public decimal ask {
            get {
                return this.askField;
            }
            set {
                this.askField = value;
            }
        }
        
        /// <remarks/>
        public string askExchange {
            get {
                return this.askExchangeField;
            }
            set {
                this.askExchangeField = value;
            }
        }
        
        /// <remarks/>
        public ushort askSize {
            get {
                return this.askSizeField;
            }
            set {
                this.askSizeField = value;
            }
        }
        
        /// <remarks/>
        public string askTime {
            get {
                return this.askTimeField;
            }
            set {
                this.askTimeField = value;
            }
        }
        
        /// <remarks/>
        public decimal bid {
            get {
                return this.bidField;
            }
            set {
                this.bidField = value;
            }
        }
        
        /// <remarks/>
        public string bidExchange {
            get {
                return this.bidExchangeField;
            }
            set {
                this.bidExchangeField = value;
            }
        }
        
        /// <remarks/>
        public ushort bidSize {
            get {
                return this.bidSizeField;
            }
            set {
                this.bidSizeField = value;
            }
        }
        
        /// <remarks/>
        public string bidTime {
            get {
                return this.bidTimeField;
            }
            set {
                this.bidTimeField = value;
            }
        }
        
        /// <remarks/>
        public decimal chgClose {
            get {
                return this.chgCloseField;
            }
            set {
                this.chgCloseField = value;
            }
        }
        
        /// <remarks/>
        public decimal chgClosePrcn {
            get {
                return this.chgClosePrcnField;
            }
            set {
                this.chgClosePrcnField = value;
            }
        }
        
        /// <remarks/>
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public byte daysToExpiration {
            get {
                return this.daysToExpirationField;
            }
            set {
                this.daysToExpirationField = value;
            }
        }
        
        /// <remarks/>
        public string dirLast {
            get {
                return this.dirLastField;
            }
            set {
                this.dirLastField = value;
            }
        }
        
        /// <remarks/>
        public decimal dividend {
            get {
                return this.dividendField;
            }
            set {
                this.dividendField = value;
            }
        }
        
        /// <remarks/>
        public decimal eps {
            get {
                return this.epsField;
            }
            set {
                this.epsField = value;
            }
        }
        
        /// <remarks/>
        public decimal estEarnings {
            get {
                return this.estEarningsField;
            }
            set {
                this.estEarningsField = value;
            }
        }
        
        /// <remarks/>
        public string exDivDate {
            get {
                return this.exDivDateField;
            }
            set {
                this.exDivDateField = value;
            }
        }
        
        /// <remarks/>
        public string exchgLastTrade {
            get {
                return this.exchgLastTradeField;
            }
            set {
                this.exchgLastTradeField = value;
            }
        }
        
        /// <remarks/>
        public string fsi {
            get {
                return this.fsiField;
            }
            set {
                this.fsiField = value;
            }
        }
        
        /// <remarks/>
        public decimal high {
            get {
                return this.highField;
            }
            set {
                this.highField = value;
            }
        }
        
        /// <remarks/>
        public decimal high52 {
            get {
                return this.high52Field;
            }
            set {
                this.high52Field = value;
            }
        }
        
        /// <remarks/>
        public decimal highAsk {
            get {
                return this.highAskField;
            }
            set {
                this.highAskField = value;
            }
        }
        
        /// <remarks/>
        public decimal highBid {
            get {
                return this.highBidField;
            }
            set {
                this.highBidField = value;
            }
        }
        
        /// <remarks/>
        public decimal lastTrade {
            get {
                return this.lastTradeField;
            }
            set {
                this.lastTradeField = value;
            }
        }
        
        /// <remarks/>
        public decimal low {
            get {
                return this.lowField;
            }
            set {
                this.lowField = value;
            }
        }
        
        /// <remarks/>
        public decimal low52 {
            get {
                return this.low52Field;
            }
            set {
                this.low52Field = value;
            }
        }
        
        /// <remarks/>
        public decimal lowAsk {
            get {
                return this.lowAskField;
            }
            set {
                this.lowAskField = value;
            }
        }
        
        /// <remarks/>
        public decimal lowBid {
            get {
                return this.lowBidField;
            }
            set {
                this.lowBidField = value;
            }
        }
        
        /// <remarks/>
        public uint numTrades {
            get {
                return this.numTradesField;
            }
            set {
                this.numTradesField = value;
            }
        }
        
        /// <remarks/>
        public decimal open {
            get {
                return this.openField;
            }
            set {
                this.openField = value;
            }
        }
        
        /// <remarks/>
        public byte openInterest {
            get {
                return this.openInterestField;
            }
            set {
                this.openInterestField = value;
            }
        }
        
        /// <remarks/>
        public object optionStyle {
            get {
                return this.optionStyleField;
            }
            set {
                this.optionStyleField = value;
            }
        }
        
        /// <remarks/>
        public object optionUnderlier {
            get {
                return this.optionUnderlierField;
            }
            set {
                this.optionUnderlierField = value;
            }
        }
        
        /// <remarks/>
        public decimal prevClose {
            get {
                return this.prevCloseField;
            }
            set {
                this.prevCloseField = value;
            }
        }
        
        /// <remarks/>
        public uint prevDayVolume {
            get {
                return this.prevDayVolumeField;
            }
            set {
                this.prevDayVolumeField = value;
            }
        }
        
        /// <remarks/>
        public string primaryExchange {
            get {
                return this.primaryExchangeField;
            }
            set {
                this.primaryExchangeField = value;
            }
        }
        
        /// <remarks/>
        public string symbolDesc {
            get {
                return this.symbolDescField;
            }
            set {
                this.symbolDescField = value;
            }
        }
        
        /// <remarks/>
        public decimal todayClose {
            get {
                return this.todayCloseField;
            }
            set {
                this.todayCloseField = value;
            }
        }
        
        /// <remarks/>
        public uint totalVolume {
            get {
                return this.totalVolumeField;
            }
            set {
                this.totalVolumeField = value;
            }
        }
        
        /// <remarks/>
        public byte upc {
            get {
                return this.upcField;
            }
            set {
                this.upcField = value;
            }
        }
        
        /// <remarks/>
        public uint volume10Day {
            get {
                return this.volume10DayField;
            }
            set {
                this.volume10DayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class QuoteResponseQuoteDataProduct {
        
        private string symbolField;
        
        private string typeField;
        
        private string exchangeField;
        
        /// <remarks/>
        public string symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string exchange {
            get {
                return this.exchangeField;
            }
            set {
                this.exchangeField = value;
            }
        }
    }
}
