//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace Sappworks.Stocks.ETrade {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AccountBalanceResponse {
        
        private uint accountIdField;
        
        private string accountTypeField;
        
        private string optionLevelField;
        
        private AccountBalanceResponseAccountBalance accountBalanceField;
        
        private AccountBalanceResponseMarginAccountBalance marginAccountBalanceField;
        
        /// <remarks/>
        public uint accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string accountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
            }
        }
        
        /// <remarks/>
        public string optionLevel {
            get {
                return this.optionLevelField;
            }
            set {
                this.optionLevelField = value;
            }
        }
        
        /// <remarks/>
        public AccountBalanceResponseAccountBalance accountBalance {
            get {
                return this.accountBalanceField;
            }
            set {
                this.accountBalanceField = value;
            }
        }
        
        /// <remarks/>
        public AccountBalanceResponseMarginAccountBalance marginAccountBalance {
            get {
                return this.marginAccountBalanceField;
            }
            set {
                this.marginAccountBalanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountBalanceResponseAccountBalance {
        
        private double cashAvailableForWithdrawalField;
        
        private double netAccountValueField;
        
        private double netCashField;
        
        private double sweepDepositAmountField;
        
        private double totalLongValueField;
        
        private double totalSecuritiesMktValueField;
        
        /// <remarks/>
        public double cashAvailableForWithdrawal {
            get {
                return this.cashAvailableForWithdrawalField;
            }
            set {
                this.cashAvailableForWithdrawalField = value;
            }
        }
        
        /// <remarks/>
        public double netAccountValue {
            get {
                return this.netAccountValueField;
            }
            set {
                this.netAccountValueField = value;
            }
        }
        
        /// <remarks/>
        public double netCash {
            get {
                return this.netCashField;
            }
            set {
                this.netCashField = value;
            }
        }
        
        /// <remarks/>
        public double sweepDepositAmount {
            get {
                return this.sweepDepositAmountField;
            }
            set {
                this.sweepDepositAmountField = value;
            }
        }
        
        /// <remarks/>
        public double totalLongValue {
            get {
                return this.totalLongValueField;
            }
            set {
                this.totalLongValueField = value;
            }
        }
        
        /// <remarks/>
        public double totalSecuritiesMktValue {
            get {
                return this.totalSecuritiesMktValueField;
            }
            set {
                this.totalSecuritiesMktValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountBalanceResponseMarginAccountBalance {
        
        private AccountBalanceResponseMarginAccountBalanceDtBalance dtBalanceField;
        
        private double fedCallField;
        
        private double marginBalanceField;
        
        private double marginBalanceWithdrawalField;
        
        private double marginEquityField;
        
        private double marginableSecuritiesField;
        
        private double maxAvailableForWithdrawalField;
        
        private double minEquityCallField;
        
        private double nonMarginableSecuritiesAndOptionsField;
        
        private double totalShortValueField;
        
        private double shortReserveField;
        
        /// <remarks/>
        public AccountBalanceResponseMarginAccountBalanceDtBalance dtBalance {
            get {
                return this.dtBalanceField;
            }
            set {
                this.dtBalanceField = value;
            }
        }
        
        /// <remarks/>
        public double fedCall {
            get {
                return this.fedCallField;
            }
            set {
                this.fedCallField = value;
            }
        }
        
        /// <remarks/>
        public double marginBalance {
            get {
                return this.marginBalanceField;
            }
            set {
                this.marginBalanceField = value;
            }
        }
        
        /// <remarks/>
        public double marginBalanceWithdrawal {
            get {
                return this.marginBalanceWithdrawalField;
            }
            set {
                this.marginBalanceWithdrawalField = value;
            }
        }
        
        /// <remarks/>
        public double marginEquity {
            get {
                return this.marginEquityField;
            }
            set {
                this.marginEquityField = value;
            }
        }
        
        /// <remarks/>
        public double marginableSecurities {
            get {
                return this.marginableSecuritiesField;
            }
            set {
                this.marginableSecuritiesField = value;
            }
        }
        
        /// <remarks/>
        public double maxAvailableForWithdrawal {
            get {
                return this.maxAvailableForWithdrawalField;
            }
            set {
                this.maxAvailableForWithdrawalField = value;
            }
        }
        
        /// <remarks/>
        public double minEquityCall {
            get {
                return this.minEquityCallField;
            }
            set {
                this.minEquityCallField = value;
            }
        }
        
        /// <remarks/>
        public double nonMarginableSecuritiesAndOptions {
            get {
                return this.nonMarginableSecuritiesAndOptionsField;
            }
            set {
                this.nonMarginableSecuritiesAndOptionsField = value;
            }
        }
        
        /// <remarks/>
        public double totalShortValue {
            get {
                return this.totalShortValueField;
            }
            set {
                this.totalShortValueField = value;
            }
        }
        
        /// <remarks/>
        public double shortReserve {
            get {
                return this.shortReserveField;
            }
            set {
                this.shortReserveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountBalanceResponseMarginAccountBalanceDtBalance {
        
        private double dtCashBalanceField;
        
        private double dtMarginBalanceField;
        
        private double dtMarginableSecuritiesField;
        
        private double dtNonMarginableSecuritiesAndOptionsField;
        
        private string dtStatusField;
        
        /// <remarks/>
        public double dtCashBalance {
            get {
                return this.dtCashBalanceField;
            }
            set {
                this.dtCashBalanceField = value;
            }
        }
        
        /// <remarks/>
        public double dtMarginBalance {
            get {
                return this.dtMarginBalanceField;
            }
            set {
                this.dtMarginBalanceField = value;
            }
        }
        
        /// <remarks/>
        public double dtMarginableSecurities {
            get {
                return this.dtMarginableSecuritiesField;
            }
            set {
                this.dtMarginableSecuritiesField = value;
            }
        }
        
        /// <remarks/>
        public double dtNonMarginableSecuritiesAndOptions {
            get {
                return this.dtNonMarginableSecuritiesAndOptionsField;
            }
            set {
                this.dtNonMarginableSecuritiesAndOptionsField = value;
            }
        }
        
        /// <remarks/>
        public string dtStatus {
            get {
                return this.dtStatusField;
            }
            set {
                this.dtStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AccountListResponse {
        
        private AccountListResponseAccount[] accountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Account")]
        public AccountListResponseAccount[] Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountListResponseAccount {
        
        private string accountDescField;
        
        private uint accountIdField;
        
        private string marginLevelField;
        
        private double netAccountValueField;
        
        private string registrationTypeField;
        
        /// <remarks/>
        public string accountDesc {
            get {
                return this.accountDescField;
            }
            set {
                this.accountDescField = value;
            }
        }
        
        /// <remarks/>
        public uint accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string marginLevel {
            get {
                return this.marginLevelField;
            }
            set {
                this.marginLevelField = value;
            }
        }
        
        /// <remarks/>
        public double netAccountValue {
            get {
                return this.netAccountValueField;
            }
            set {
                this.netAccountValueField = value;
            }
        }
        
        /// <remarks/>
        public string registrationType {
            get {
                return this.registrationTypeField;
            }
            set {
                this.registrationTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AccountPositionsResponse {
        
        private uint accountIdField;
        
        private short countField;
        
        private string markerField;
        
        private AccountPositionsResponseAccountPosition[] accountPositionsField;
        
        /// <remarks/>
        public uint accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public short count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public string marker {
            get {
                return this.markerField;
            }
            set {
                this.markerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AccountPosition", IsNullable=false)]
        public AccountPositionsResponseAccountPosition[] AccountPositions {
            get {
                return this.accountPositionsField;
            }
            set {
                this.accountPositionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountPositionsResponseAccountPosition {
        
        private double costBasisField;
        
        private string descriptionField;
        
        private string longOrShortField;
        
        private bool marginableField;
        
        private AccountPositionsResponseAccountPositionProductId productIdField;
        
        private double qtyField;
        
        private double marketValueField;
        
        /// <remarks/>
        public double costBasis {
            get {
                return this.costBasisField;
            }
            set {
                this.costBasisField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string longOrShort {
            get {
                return this.longOrShortField;
            }
            set {
                this.longOrShortField = value;
            }
        }
        
        /// <remarks/>
        public bool marginable {
            get {
                return this.marginableField;
            }
            set {
                this.marginableField = value;
            }
        }
        
        /// <remarks/>
        public AccountPositionsResponseAccountPositionProductId productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public double qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public double marketValue {
            get {
                return this.marketValueField;
            }
            set {
                this.marketValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountPositionsResponseAccountPositionProductId {
        
        private string symbolField;
        
        private string typeCodeField;
        
        /// <remarks/>
        public string symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string typeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class GetOrderListResponse {
        
        private GetOrderListResponseOrderListResponse orderListResponseField;
        
        /// <remarks/>
        public GetOrderListResponseOrderListResponse orderListResponse {
            get {
                return this.orderListResponseField;
            }
            set {
                this.orderListResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetOrderListResponseOrderListResponse {
        
        private int countField;
        
        private string markerField;
        
        private GetOrderListResponseOrderListResponseOrderDetails[] orderDetailsField;
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public string marker {
            get {
                return this.markerField;
            }
            set {
                this.markerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OrderDetails", IsNullable=false)]
        public GetOrderListResponseOrderListResponseOrderDetails[] orderDetails {
            get {
                return this.orderDetailsField;
            }
            set {
                this.orderDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetOrderListResponseOrderListResponseOrderDetails {
        
        private GetOrderListResponseOrderListResponseOrderDetailsOrder orderField;
        
        /// <remarks/>
        public GetOrderListResponseOrderListResponseOrderDetailsOrder order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetOrderListResponseOrderListResponseOrderDetailsOrder {
        
        private long orderIdField;
        
        private ulong orderPlacedTimeField;
        
        private ulong orderExecutedTimeField;
        
        private bool orderExecutedTimeFieldSpecified;
        
        private double orderValueField;
        
        private string orderStatusField;
        
        private string orderTypeField;
        
        private string orderTermField;
        
        private string priceTypeField;
        
        private double limitPriceField;
        
        private double stopPriceField;
        
        private GetOrderListResponseOrderListResponseOrderDetailsOrderLegDetails[] legDetailsField;
        
        private long replacedByOrderIdField;
        
        private bool replacedByOrderIdFieldSpecified;
        
        private bool allOrNoneField;
        
        /// <remarks/>
        public long orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public ulong orderPlacedTime {
            get {
                return this.orderPlacedTimeField;
            }
            set {
                this.orderPlacedTimeField = value;
            }
        }
        
        /// <remarks/>
        public ulong orderExecutedTime {
            get {
                return this.orderExecutedTimeField;
            }
            set {
                this.orderExecutedTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderExecutedTimeSpecified {
            get {
                return this.orderExecutedTimeFieldSpecified;
            }
            set {
                this.orderExecutedTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double orderValue {
            get {
                return this.orderValueField;
            }
            set {
                this.orderValueField = value;
            }
        }
        
        /// <remarks/>
        public string orderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        public string orderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        public string orderTerm {
            get {
                return this.orderTermField;
            }
            set {
                this.orderTermField = value;
            }
        }
        
        /// <remarks/>
        public string priceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        public double limitPrice {
            get {
                return this.limitPriceField;
            }
            set {
                this.limitPriceField = value;
            }
        }
        
        /// <remarks/>
        public double stopPrice {
            get {
                return this.stopPriceField;
            }
            set {
                this.stopPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LegDetails", IsNullable=false)]
        public GetOrderListResponseOrderListResponseOrderDetailsOrderLegDetails[] legDetails {
            get {
                return this.legDetailsField;
            }
            set {
                this.legDetailsField = value;
            }
        }
        
        /// <remarks/>
        public long replacedByOrderId {
            get {
                return this.replacedByOrderIdField;
            }
            set {
                this.replacedByOrderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool replacedByOrderIdSpecified {
            get {
                return this.replacedByOrderIdFieldSpecified;
            }
            set {
                this.replacedByOrderIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool allOrNone {
            get {
                return this.allOrNoneField;
            }
            set {
                this.allOrNoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetOrderListResponseOrderListResponseOrderDetailsOrderLegDetails {
        
        private long legNumberField;
        
        private GetOrderListResponseOrderListResponseOrderDetailsOrderLegDetailsSymbolInfo symbolInfoField;
        
        private string symbolDescriptionField;
        
        private string orderActionField;
        
        private double orderedQuantityField;
        
        private double filledQuantityField;
        
        private double executedPriceField;
        
        private double estimatedCommissionField;
        
        private double estimatedFeesField;
        
        /// <remarks/>
        public long legNumber {
            get {
                return this.legNumberField;
            }
            set {
                this.legNumberField = value;
            }
        }
        
        /// <remarks/>
        public GetOrderListResponseOrderListResponseOrderDetailsOrderLegDetailsSymbolInfo symbolInfo {
            get {
                return this.symbolInfoField;
            }
            set {
                this.symbolInfoField = value;
            }
        }
        
        /// <remarks/>
        public string symbolDescription {
            get {
                return this.symbolDescriptionField;
            }
            set {
                this.symbolDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string orderAction {
            get {
                return this.orderActionField;
            }
            set {
                this.orderActionField = value;
            }
        }
        
        /// <remarks/>
        public double orderedQuantity {
            get {
                return this.orderedQuantityField;
            }
            set {
                this.orderedQuantityField = value;
            }
        }
        
        /// <remarks/>
        public double filledQuantity {
            get {
                return this.filledQuantityField;
            }
            set {
                this.filledQuantityField = value;
            }
        }
        
        /// <remarks/>
        public double executedPrice {
            get {
                return this.executedPriceField;
            }
            set {
                this.executedPriceField = value;
            }
        }
        
        /// <remarks/>
        public double estimatedCommission {
            get {
                return this.estimatedCommissionField;
            }
            set {
                this.estimatedCommissionField = value;
            }
        }
        
        /// <remarks/>
        public double estimatedFees {
            get {
                return this.estimatedFeesField;
            }
            set {
                this.estimatedFeesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetOrderListResponseOrderListResponseOrderDetailsOrderLegDetailsSymbolInfo {
        
        private string symbolField;
        
        private string callPutField;
        
        private short expYearField;
        
        private bool expYearFieldSpecified;
        
        private byte expMonthField;
        
        private bool expMonthFieldSpecified;
        
        private byte expDayField;
        
        private bool expDayFieldSpecified;
        
        private double strikePriceField;
        
        private bool strikePriceFieldSpecified;
        
        /// <remarks/>
        public string symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string callPut {
            get {
                return this.callPutField;
            }
            set {
                this.callPutField = value;
            }
        }
        
        /// <remarks/>
        public short expYear {
            get {
                return this.expYearField;
            }
            set {
                this.expYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expYearSpecified {
            get {
                return this.expYearFieldSpecified;
            }
            set {
                this.expYearFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public byte expMonth {
            get {
                return this.expMonthField;
            }
            set {
                this.expMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expMonthSpecified {
            get {
                return this.expMonthFieldSpecified;
            }
            set {
                this.expMonthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public byte expDay {
            get {
                return this.expDayField;
            }
            set {
                this.expDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expDaySpecified {
            get {
                return this.expDayFieldSpecified;
            }
            set {
                this.expDayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double strikePrice {
            get {
                return this.strikePriceField;
            }
            set {
                this.strikePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool strikePriceSpecified {
            get {
                return this.strikePriceFieldSpecified;
            }
            set {
                this.strikePriceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PlaceEquityOrder {
        
        private PlaceEquityOrderEquityOrderRequest itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EquityOrderRequest")]
        public PlaceEquityOrderEquityOrderRequest Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PlaceEquityOrderEquityOrderRequest {
        
        private uint accountIdField;
        
        private string clientOrderIdField;
        
        private double limitPriceField;
        
        private bool limitPriceFieldSpecified;
        
        private long previewIdField;
        
        private bool previewIdFieldSpecified;
        
        private double stopPriceField;
        
        private bool stopPriceFieldSpecified;
        
        private bool allOrNoneField;
        
        private bool allOrNoneFieldSpecified;
        
        private int quantityField;
        
        private bool reserveOrderField;
        
        private bool reserveOrderFieldSpecified;
        
        private int reserveQuantityField;
        
        private bool reserveQuantityFieldSpecified;
        
        private string symbolField;
        
        private string orderActionField;
        
        private string priceTypeField;
        
        private string routingDestinationField;
        
        private string marketSessionField;
        
        private string orderTermField;
        
        /// <remarks/>
        public uint accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string clientOrderId {
            get {
                return this.clientOrderIdField;
            }
            set {
                this.clientOrderIdField = value;
            }
        }
        
        /// <remarks/>
        public double limitPrice {
            get {
                return this.limitPriceField;
            }
            set {
                this.limitPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool limitPriceSpecified {
            get {
                return this.limitPriceFieldSpecified;
            }
            set {
                this.limitPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long previewId {
            get {
                return this.previewIdField;
            }
            set {
                this.previewIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool previewIdSpecified {
            get {
                return this.previewIdFieldSpecified;
            }
            set {
                this.previewIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double stopPrice {
            get {
                return this.stopPriceField;
            }
            set {
                this.stopPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stopPriceSpecified {
            get {
                return this.stopPriceFieldSpecified;
            }
            set {
                this.stopPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool allOrNone {
            get {
                return this.allOrNoneField;
            }
            set {
                this.allOrNoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool allOrNoneSpecified {
            get {
                return this.allOrNoneFieldSpecified;
            }
            set {
                this.allOrNoneFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public bool reserveOrder {
            get {
                return this.reserveOrderField;
            }
            set {
                this.reserveOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reserveOrderSpecified {
            get {
                return this.reserveOrderFieldSpecified;
            }
            set {
                this.reserveOrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int reserveQuantity {
            get {
                return this.reserveQuantityField;
            }
            set {
                this.reserveQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reserveQuantitySpecified {
            get {
                return this.reserveQuantityFieldSpecified;
            }
            set {
                this.reserveQuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string orderAction {
            get {
                return this.orderActionField;
            }
            set {
                this.orderActionField = value;
            }
        }
        
        /// <remarks/>
        public string priceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string routingDestination {
            get {
                return this.routingDestinationField;
            }
            set {
                this.routingDestinationField = value;
            }
        }
        
        /// <remarks/>
        public string marketSession {
            get {
                return this.marketSessionField;
            }
            set {
                this.marketSessionField = value;
            }
        }
        
        /// <remarks/>
        public string orderTerm {
            get {
                return this.orderTermField;
            }
            set {
                this.orderTermField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PlaceEquityOrderResponse {
        
        private PlaceEquityOrderResponseEquityOrderResponse itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("equityOrderResponse")]
        public PlaceEquityOrderResponseEquityOrderResponse Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PlaceEquityOrderResponseEquityOrderResponse {
        
        private int accountIdField;
        
        private bool accountIdFieldSpecified;
        
        private bool allOrNoneField;
        
        private bool allOrNoneFieldSpecified;
        
        private double estimatedCommissionField;
        
        private bool estimatedCommissionFieldSpecified;
        
        private double estimatedTotalAmountField;
        
        private bool estimatedTotalAmountFieldSpecified;
        
        private int orderNumField;
        
        private bool orderNumFieldSpecified;
        
        private long orderTimeField;
        
        private bool orderTimeFieldSpecified;
        
        private int quantityField;
        
        private bool quantityFieldSpecified;
        
        private bool reserveOrderField;
        
        private bool reserveOrderFieldSpecified;
        
        private int reserveQuantityField;
        
        private bool reserveQuantityFieldSpecified;
        
        private string orderTermField;
        
        private double limitPriceField;
        
        private bool limitPriceFieldSpecified;
        
        private double stopPriceField;
        
        private bool stopPriceFieldSpecified;
        
        private string symbolDescField;
        
        private string symbolField;
        
        private string orderActionField;
        
        private string priceTypeField;
        
        private PlaceEquityOrderResponseEquityOrderResponseMessageList[] messageListField;
        
        /// <remarks/>
        public int accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accountIdSpecified {
            get {
                return this.accountIdFieldSpecified;
            }
            set {
                this.accountIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool allOrNone {
            get {
                return this.allOrNoneField;
            }
            set {
                this.allOrNoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool allOrNoneSpecified {
            get {
                return this.allOrNoneFieldSpecified;
            }
            set {
                this.allOrNoneFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double estimatedCommission {
            get {
                return this.estimatedCommissionField;
            }
            set {
                this.estimatedCommissionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estimatedCommissionSpecified {
            get {
                return this.estimatedCommissionFieldSpecified;
            }
            set {
                this.estimatedCommissionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double estimatedTotalAmount {
            get {
                return this.estimatedTotalAmountField;
            }
            set {
                this.estimatedTotalAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estimatedTotalAmountSpecified {
            get {
                return this.estimatedTotalAmountFieldSpecified;
            }
            set {
                this.estimatedTotalAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int orderNum {
            get {
                return this.orderNumField;
            }
            set {
                this.orderNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderNumSpecified {
            get {
                return this.orderNumFieldSpecified;
            }
            set {
                this.orderNumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long orderTime {
            get {
                return this.orderTimeField;
            }
            set {
                this.orderTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderTimeSpecified {
            get {
                return this.orderTimeFieldSpecified;
            }
            set {
                this.orderTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool reserveOrder {
            get {
                return this.reserveOrderField;
            }
            set {
                this.reserveOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reserveOrderSpecified {
            get {
                return this.reserveOrderFieldSpecified;
            }
            set {
                this.reserveOrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int reserveQuantity {
            get {
                return this.reserveQuantityField;
            }
            set {
                this.reserveQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reserveQuantitySpecified {
            get {
                return this.reserveQuantityFieldSpecified;
            }
            set {
                this.reserveQuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string orderTerm {
            get {
                return this.orderTermField;
            }
            set {
                this.orderTermField = value;
            }
        }
        
        /// <remarks/>
        public double limitPrice {
            get {
                return this.limitPriceField;
            }
            set {
                this.limitPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool limitPriceSpecified {
            get {
                return this.limitPriceFieldSpecified;
            }
            set {
                this.limitPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double stopPrice {
            get {
                return this.stopPriceField;
            }
            set {
                this.stopPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stopPriceSpecified {
            get {
                return this.stopPriceFieldSpecified;
            }
            set {
                this.stopPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string symbolDesc {
            get {
                return this.symbolDescField;
            }
            set {
                this.symbolDescField = value;
            }
        }
        
        /// <remarks/>
        public string symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string orderAction {
            get {
                return this.orderActionField;
            }
            set {
                this.orderActionField = value;
            }
        }
        
        /// <remarks/>
        public string priceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageList")]
        public PlaceEquityOrderResponseEquityOrderResponseMessageList[] messageList {
            get {
                return this.messageListField;
            }
            set {
                this.messageListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PlaceEquityOrderResponseEquityOrderResponseMessageList {
        
        private PlaceEquityOrderResponseEquityOrderResponseMessageListMessage messageField;
        
        /// <remarks/>
        public PlaceEquityOrderResponseEquityOrderResponseMessageListMessage message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PlaceEquityOrderResponseEquityOrderResponseMessageListMessage {
        
        private string msgDescField;
        
        private int msgCodeField;
        
        private bool msgCodeFieldSpecified;
        
        /// <remarks/>
        public string msgDesc {
            get {
                return this.msgDescField;
            }
            set {
                this.msgDescField = value;
            }
        }
        
        /// <remarks/>
        public int msgCode {
            get {
                return this.msgCodeField;
            }
            set {
                this.msgCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool msgCodeSpecified {
            get {
                return this.msgCodeFieldSpecified;
            }
            set {
                this.msgCodeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class QuoteResponse {
        
        private QuoteResponseQuoteData[] quoteDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QuoteData")]
        public QuoteResponseQuoteData[] QuoteData {
            get {
                return this.quoteDataField;
            }
            set {
                this.quoteDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class QuoteResponseQuoteData {
        
        private QuoteResponseQuoteDataAll allField;
        
        private string dateTimeField;
        
        private QuoteResponseQuoteDataProduct productField;
        
        /// <remarks/>
        public QuoteResponseQuoteDataAll all {
            get {
                return this.allField;
            }
            set {
                this.allField = value;
            }
        }
        
        /// <remarks/>
        public string dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        public QuoteResponseQuoteDataProduct product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class QuoteResponseQuoteDataAll {
        
        private bool adjNonAdjFlagField;
        
        private double annualDividendField;
        
        private double askField;
        
        private string askExchangeField;
        
        private uint askSizeField;
        
        private string askTimeField;
        
        private double bidField;
        
        private string bidExchangeField;
        
        private uint bidSizeField;
        
        private string bidTimeField;
        
        private double chgCloseField;
        
        private double chgClosePrcnField;
        
        private string companyNameField;
        
        private uint daysToExpirationField;
        
        private string dirLastField;
        
        private double dividendField;
        
        private double epsField;
        
        private double estEarningsField;
        
        private string exDivDateField;
        
        private string exchgLastTradeField;
        
        private string fsiField;
        
        private double highField;
        
        private double high52Field;
        
        private double highAskField;
        
        private double highBidField;
        
        private double lastTradeField;
        
        private double lowField;
        
        private double low52Field;
        
        private double lowAskField;
        
        private double lowBidField;
        
        private uint numTradesField;
        
        private double openField;
        
        private long openInterestField;
        
        private object optionStyleField;
        
        private object optionUnderlierField;
        
        private double prevCloseField;
        
        private long prevDayVolumeField;
        
        private string primaryExchangeField;
        
        private string symbolDescField;
        
        private double todayCloseField;
        
        private long totalVolumeField;
        
        private long upcField;
        
        private long volume10DayField;
        
        /// <remarks/>
        public bool adjNonAdjFlag {
            get {
                return this.adjNonAdjFlagField;
            }
            set {
                this.adjNonAdjFlagField = value;
            }
        }
        
        /// <remarks/>
        public double annualDividend {
            get {
                return this.annualDividendField;
            }
            set {
                this.annualDividendField = value;
            }
        }
        
        /// <remarks/>
        public double ask {
            get {
                return this.askField;
            }
            set {
                this.askField = value;
            }
        }
        
        /// <remarks/>
        public string askExchange {
            get {
                return this.askExchangeField;
            }
            set {
                this.askExchangeField = value;
            }
        }
        
        /// <remarks/>
        public uint askSize {
            get {
                return this.askSizeField;
            }
            set {
                this.askSizeField = value;
            }
        }
        
        /// <remarks/>
        public string askTime {
            get {
                return this.askTimeField;
            }
            set {
                this.askTimeField = value;
            }
        }
        
        /// <remarks/>
        public double bid {
            get {
                return this.bidField;
            }
            set {
                this.bidField = value;
            }
        }
        
        /// <remarks/>
        public string bidExchange {
            get {
                return this.bidExchangeField;
            }
            set {
                this.bidExchangeField = value;
            }
        }
        
        /// <remarks/>
        public uint bidSize {
            get {
                return this.bidSizeField;
            }
            set {
                this.bidSizeField = value;
            }
        }
        
        /// <remarks/>
        public string bidTime {
            get {
                return this.bidTimeField;
            }
            set {
                this.bidTimeField = value;
            }
        }
        
        /// <remarks/>
        public double chgClose {
            get {
                return this.chgCloseField;
            }
            set {
                this.chgCloseField = value;
            }
        }
        
        /// <remarks/>
        public double chgClosePrcn {
            get {
                return this.chgClosePrcnField;
            }
            set {
                this.chgClosePrcnField = value;
            }
        }
        
        /// <remarks/>
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public uint daysToExpiration {
            get {
                return this.daysToExpirationField;
            }
            set {
                this.daysToExpirationField = value;
            }
        }
        
        /// <remarks/>
        public string dirLast {
            get {
                return this.dirLastField;
            }
            set {
                this.dirLastField = value;
            }
        }
        
        /// <remarks/>
        public double dividend {
            get {
                return this.dividendField;
            }
            set {
                this.dividendField = value;
            }
        }
        
        /// <remarks/>
        public double eps {
            get {
                return this.epsField;
            }
            set {
                this.epsField = value;
            }
        }
        
        /// <remarks/>
        public double estEarnings {
            get {
                return this.estEarningsField;
            }
            set {
                this.estEarningsField = value;
            }
        }
        
        /// <remarks/>
        public string exDivDate {
            get {
                return this.exDivDateField;
            }
            set {
                this.exDivDateField = value;
            }
        }
        
        /// <remarks/>
        public string exchgLastTrade {
            get {
                return this.exchgLastTradeField;
            }
            set {
                this.exchgLastTradeField = value;
            }
        }
        
        /// <remarks/>
        public string fsi {
            get {
                return this.fsiField;
            }
            set {
                this.fsiField = value;
            }
        }
        
        /// <remarks/>
        public double high {
            get {
                return this.highField;
            }
            set {
                this.highField = value;
            }
        }
        
        /// <remarks/>
        public double high52 {
            get {
                return this.high52Field;
            }
            set {
                this.high52Field = value;
            }
        }
        
        /// <remarks/>
        public double highAsk {
            get {
                return this.highAskField;
            }
            set {
                this.highAskField = value;
            }
        }
        
        /// <remarks/>
        public double highBid {
            get {
                return this.highBidField;
            }
            set {
                this.highBidField = value;
            }
        }
        
        /// <remarks/>
        public double lastTrade {
            get {
                return this.lastTradeField;
            }
            set {
                this.lastTradeField = value;
            }
        }
        
        /// <remarks/>
        public double low {
            get {
                return this.lowField;
            }
            set {
                this.lowField = value;
            }
        }
        
        /// <remarks/>
        public double low52 {
            get {
                return this.low52Field;
            }
            set {
                this.low52Field = value;
            }
        }
        
        /// <remarks/>
        public double lowAsk {
            get {
                return this.lowAskField;
            }
            set {
                this.lowAskField = value;
            }
        }
        
        /// <remarks/>
        public double lowBid {
            get {
                return this.lowBidField;
            }
            set {
                this.lowBidField = value;
            }
        }
        
        /// <remarks/>
        public uint numTrades {
            get {
                return this.numTradesField;
            }
            set {
                this.numTradesField = value;
            }
        }
        
        /// <remarks/>
        public double open {
            get {
                return this.openField;
            }
            set {
                this.openField = value;
            }
        }
        
        /// <remarks/>
        public long openInterest {
            get {
                return this.openInterestField;
            }
            set {
                this.openInterestField = value;
            }
        }
        
        /// <remarks/>
        public object optionStyle {
            get {
                return this.optionStyleField;
            }
            set {
                this.optionStyleField = value;
            }
        }
        
        /// <remarks/>
        public object optionUnderlier {
            get {
                return this.optionUnderlierField;
            }
            set {
                this.optionUnderlierField = value;
            }
        }
        
        /// <remarks/>
        public double prevClose {
            get {
                return this.prevCloseField;
            }
            set {
                this.prevCloseField = value;
            }
        }
        
        /// <remarks/>
        public long prevDayVolume {
            get {
                return this.prevDayVolumeField;
            }
            set {
                this.prevDayVolumeField = value;
            }
        }
        
        /// <remarks/>
        public string primaryExchange {
            get {
                return this.primaryExchangeField;
            }
            set {
                this.primaryExchangeField = value;
            }
        }
        
        /// <remarks/>
        public string symbolDesc {
            get {
                return this.symbolDescField;
            }
            set {
                this.symbolDescField = value;
            }
        }
        
        /// <remarks/>
        public double todayClose {
            get {
                return this.todayCloseField;
            }
            set {
                this.todayCloseField = value;
            }
        }
        
        /// <remarks/>
        public long totalVolume {
            get {
                return this.totalVolumeField;
            }
            set {
                this.totalVolumeField = value;
            }
        }
        
        /// <remarks/>
        public long upc {
            get {
                return this.upcField;
            }
            set {
                this.upcField = value;
            }
        }
        
        /// <remarks/>
        public long volume10Day {
            get {
                return this.volume10DayField;
            }
            set {
                this.volume10DayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class QuoteResponseQuoteDataProduct {
        
        private string symbolField;
        
        private string typeField;
        
        private string exchangeField;
        
        /// <remarks/>
        public string symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string exchange {
            get {
                return this.exchangeField;
            }
            set {
                this.exchangeField = value;
            }
        }
    }
}
